default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: Application_development

test:
  <<: *default
  database: Application_test

production:
  <<: *default
  database: Application_production
  username: Application
  password: <%= ENV['DATABASE_PASSWORD'] %>